### ISSUE TITLE
Activation issue

### ISSUE THREAD

**Issue by PSHacks** [Brayan-Villa/iCloud-Bypass-Server#1]
ideviceactivation says "Failed to activate device with record."...

**Comment by Brayan-Villa** [comment]
Apunte a mi servidor 
https://ex3cution3ractivation.000webhostapp.com/activx.php

**Comment by PSHacks** [comment]
> Apunte a mi servidor
> https://ex3cution3ractivation.000webhostapp.com/activx.php

Still same.. Failed to activate device with record.. iPhone 5c last iOS GSM

**Comment by PSHacks** [comment]
> Apunte a mi servidor
> https://ex3cution3ractivation.000webhostapp.com/activx.php

Oh btw I have another, activated iphone 5c, i can make ideviceactivation -d with that phone to see what difference between your server response and official apple's
 
EDIT::
Basically I can turn off FMI, deactivate iphone, and after that activate with debug flag, and send to you all requests..

**Comment by Brayan-Villa** [comment]
No brother, you're wrong, neglect, I'll explain. For your device to activate you will need to connect it to Apple's official servers, if it has activation lock enter the correct data, this php is for account break tests for developers of iCloud derivation tools

**Comment by PSHacks** [comment]
Oh, its sad.. I have an iphone 6s on activation lock, and when i found ur repo it gives to me a hope that i can get working phone without paying 40$ (i got phone for 15$ btw)..

**Comment by Brayan-Villa** [comment]
Check my new repository and try activate your device free and full.
The free services made free is temporally

**Comment by PSHacks** [comment]
> Check my new repository and try activate your device free and full.
> The free services made free is temporally

Does it will get cellular work on meid??? I'll make a donation for u if it will!

**Comment by Brayan-Villa** [comment]
Not brother if you require activate the Cellular Data of your device. Buy service the Minacriss

**Comment by PSHacks** [comment]
> Not brother if you require activate the Cellular Data of your device. Buy service the Minacriss

Thats what im saying a few posts ago.. mina too much overpriced, its ok for new iphones but old 6s cost 40$ considering that it costs 20, idk.. Anyways, issue closed, thank you for your work and all replies man. Good luck!

**Comment by xr3move** [comment]
This guy is a scammer, be careful, never make any purchases.
