### ISSUE TITLE
MEID Activation

### ISSUE THREAD

**Issue by F1R3W4LL404** [Brayan-Villa/iCloud-Bypass-Server#2]
Failed to activate device MEID, Any solution?

**Comment by Brayan-Villa** [comment]
Apunte a mi servidor
https://ex3cution3ractivation.000webhostapp.com/activx.php

**Comment by F1R3W4LL404** [comment]
> Apunte a mi servidor
> https://ex3cution3ractivation.000webhostapp.com/activx.php

Podrias pasarme el php?

**Comment by Brayan-Villa** [comment]
I'm sorry brother, it's my current project and it has cost me a lot to create it from 0. But point to my server, no problem,
